### ISSUE TITLE
Reboot stops driver from working

### ISSUE THREAD

**Issue by kingelilol** [mback2k/wiasane#42]
I'm using the Windows 10 64-bit edition.
After the setup, everything works as intended but after I reboot my PC I can't scan anymore.
Maby related to #9 

For example, NAPS2 throws an error with the title "An error occurred with the scanning driver"
```
NAPS2.Scan.Exceptions.ScanDriverUnknownException: An error occurred with the scanning driver. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x8021000A
   at WIA.CommonDialogClass.ShowTransfer(Item Item, String FormatID, Boolean CancelError)
   at NAPS2.Scan.Wia.ForegroundWiaTransfer.<>c__DisplayClass2_0.<Transfer>b__1(WiaState wia)
   at NAPS2.Scan.Wia.WiaBackgroundEventLoop.<>c__DisplayClass8_0`1.<GetSync>b__0(WiaState wia)
   at NAPS2.Scan.Wia.WiaBackgroundEventLoop.<>c__DisplayClass7_0.<DoSync>b__0()
   --- End of inner exception stack trace ---
   at NAPS2.Scan.Wia.WiaApi.ThrowDeviceError(COMException e)
   at NAPS2.Scan.Wia.WiaApi.ThrowDeviceError(Exception error)
   at NAPS2.Scan.Wia.WiaBackgroundEventLoop.DoSync(Action`1 action)
   at NAPS2.Scan.Wia.WiaBackgroundEventLoop.GetSync[T](Func`2 action)
   at NAPS2.Scan.Wia.ForegroundWiaTransfer.Transfer(Int32 pageNumber, WiaBackgroundEventLoop eventLoop, String format)
   at NAPS2.Scan.Wia.WiaScanDriver.TransferImage(WiaBackgroundEventLoop eventLoop, Int32 pageNumber, Boolean& cancel)
   at NAPS2.Scan.Wia.WiaScanDriver.<ScanInternal>d__13.MoveNext()
   at NAPS2.Scan.ScanPerformer.PerformScan(ScanProfile scanProfile, ScanParams scanParams, IWin32Window dialogParent, ISaveNotify notify, Action`1 imageCallback)
```

I tried running your "winsane-dbg.exe" but the output from before and after the reboot are identical.
The following steps are solving this issue until the next reboot.

> I had a Code 22 (Device disabled) issue on Windows 10 1803. 
> The underlying cause appeared to be that the scanner got installed with the default localhost:6566 address, with no chance to set the correct IP address of saned.
> 
> I could work it around with these steps:
> * Go to Device Manager. See that the scanner device under "Imaging devices" is disabled with Code 22.
> * Right-click on the scanner device, and select "Enable device". The disabled icon should disappear.
> * Right-click on the scanner device again, and select "Properties". The device properties dialog will open.
> * Navigate to the Driver tab, and click "Update driver". The update drivers wizard will open.
> * Click "Browse my computer for driver software".
> * Click "Let me pick from a list of available drivers on my computer". A list should appear, containing the `Scanner Access Now Easy - WIA Driver` item.
> * Select `Scanner Access Now Easy - WIA Driver`. Click Next.
> 
> At this point, installation should begin, and the IP and port config dialog should appear, where the correct IP and port can be set.

_Originally posted by @orosam in https://github.com/mback2k/wiasane/issues/36#issuecomment-398142675_

Could there be any problem with my configuration? Or what could cause this problem?

**Comment by oleua** [comment]
The same :(
